modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/byAdam/Minecraft-Facecam/issues" #optional
[[mods]] #mandatory
modId="facecam" #mandatory
version="0.1.0" #mandatory
displayName="Minecraft Facecam" #mandatory
updateJSONURL="http://byadam.net/facecam/update.json" #optional

## Information
displayURL="http://byadam.net/facecam" #optional

# In root of the mod JAR
logoFile="logo.png" #optional
# A text field displayed in the mod UI
credits="Adam Brady" #optional
# A text field displayed in the mod UI
authors="Adam Brady" #optional
# The description text for the mod (multi line!) (#mandatory)
description="Replace your player's face with a live facecam."